export const EXERCISE_LIST = [
  "Barbell Back Squat",
  "Barbell Front Squat",
  "Barbell Deadlift",
  "Barbell Bench Press",
  "Barbell Overhead Press",
  "Barbell Row",
  "Barbell Romanian Deadlift",
  "Barbell Hip Thrust",
  "Barbell Lunge",
  "Barbell Sumo Deadlift",
  "Barbell Incline Bench Press",
  "Barbell Close Grip Bench Press",
  "Barbell Curl",
  "Barbell Skull Crusher",
  "Barbell Good Morning",
  "Barbell Shrug",
  "Barbell Upright Row",
  "Barbell Power Clean",
  "Barbell Hang Clean",
  "Barbell Snatch",
  "Dumbbell Bench Press",
  "Dumbbell Shoulder Press",
  "Dumbbell Row",
  "Dumbbell Romanian Deadlift",
  "Dumbbell Lateral Raise",
  "Dumbbell Front Raise",
  "Dumbbell Curl",
  "Dumbbell Hammer Curl",
  "Dumbbell Tricep Kickback",
  "Dumbbell Incline Bench Press",
  "Dumbbell Fly",
  "Dumbbell Incline Fly",
  "Dumbbell Goblet Squat",
  "Dumbbell Lunge",
  "Dumbbell Step Up",
  "Dumbbell Hip Thrust",
  "Dumbbell Shrug",
  "Dumbbell Skull Crusher",
  "Dumbbell Reverse Fly",
  "Dumbbell Arnold Press",
  "Dumbbell Concentration Curl",
  "Dumbbell Wrist Curl",
  "Dumbbell Calf Raise",
  "Dumbbell Pullover",
  "Dumbbell Split Squat",
  "Lat Pulldown",
  "Seated Cable Row",
  "Cable Fly",
  "Cable Lateral Raise",
  "Cable Tricep Pushdown",
  "Cable Overhead Tricep Extension",
  "Cable Curl",
  "Cable Face Pull",
  "Cable Pull Through",
  "Cable Hip Abduction",
  "Cable Woodchop",
  "Cable Crunch",
  "Leg Press",
  "Leg Extension",
  "Leg Curl (Lying)",
  "Leg Curl (Seated)",
  "Hack Squat",
  "Smith Machine Squat",
  "Smith Machine Bench Press",
  "Chest Press Machine",
  "Shoulder Press Machine",
  "Pec Deck Machine",
  "Seated Row Machine",
  "Lat Pullover Machine",
  "Hip Abduction Machine",
  "Hip Adduction Machine",
  "Calf Raise Machine (Standing)",
  "Calf Raise Machine (Seated)",
  "Back Extension Machine",
  "Ab Crunch Machine",
  "Pull-Up",
  "Chin-Up",
  "Wide Grip Pull-Up",
  "Muscle-Up",
  "Push-Up",
  "Wide Push-Up",
  "Diamond Push-Up",
  "Decline Push-Up",
  "Pike Push-Up",
  "Archer Push-Up",
  "Handstand Push-Up",
  "Dip",
  "Tricep Dip (Bench)",
  "Inverted Row",
  "Body Saw",
  "Plank",
  "Side Plank",
  "Hollow Body Hold",
  "L-Sit",
  "Front Lever",
  "Back Lever",
  "Human Flag",
  "Pistol Squat",
  "Bulgarian Split Squat",
  "Bodyweight Squat",
  "Jump Squat",
  "Walking Lunge",
  "Reverse Lunge",
  "Glute Bridge",
  "Single Leg Glute Bridge",
  "Donkey Kick",
  "Fire Hydrant",
  "Clamshell",
  "Bodyweight Hip Thrust",
  "Nordic Curl",
  "Sit-Up",
  "Crunch",
  "Bicycle Crunch",
  "Leg Raise",
  "Hanging Leg Raise",
  "Hanging Knee Raise",
  "Dragon Flag",
  "Ab Wheel Rollout",
  "Russian Twist",
  "V-Up",
  "Toe Touch",
  "Mountain Climber",
  "Burpee",
  "Kettlebell Swing",
  "Kettlebell Goblet Squat",
  "Kettlebell Clean",
  "Kettlebell Snatch",
  "Kettlebell Turkish Get-Up",
  "Kettlebell Press",
  "Kettlebell Row",
  "Kettlebell Deadlift",
  "Kettlebell Halo",
  "EZ Bar Curl",
  "EZ Bar Skull Crusher",
  "EZ Bar Overhead Extension",
  "Preacher Curl",
  "Resistance Band Squat",
  "Resistance Band Row",
  "Resistance Band Pull Apart",
  "Resistance Band Curl",
  "Resistance Band Tricep Pushdown",
  "Resistance Band Lateral Walk",
  "Resistance Band Hip Thrust",
  "Dumbbell Zottman Curl",
  "Dumbbell Spider Curl",
  "Hyperextension (Back Extension)",
  "Farmer's Walk",
  "Sled Push",
  "Battle Ropes",
  "Box Jump",
];
